name: ELI Watchdog PR

on: [push, pull_request]

jobs:
  build:
    name: Watchdog

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Checkout ELI
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/osmlab/editor-layer-index.git

      - name: Run Watchdog
        run: |
          python watchdog.py editor-layer-index/sources

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.5.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web # The folder the action should deploy.
