name: ELI Watchdog Manual

on: [push]

jobs:
  watchdog:
    name: Watchdog
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bump]') && !contains(github.event.head_commit.message, 'Bump')"

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Checkout ELI
        run: |
          git clone --depth=1 --branch=gh-pages https://github.com/osmlab/editor-layer-index.git

      - name: Download Broken Sources
        run: |
          wget https://raw.githubusercontent.com/rbuffat/eli_watchdog/gh-pages/broken.json -P web
          cat web/broken.json

      - name: Run Watchdog
        env:
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
        run: |
          python watchdog.py editor-layer-index/sources

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: web # The folder the action should deploy.
